# fly.toml file generated for learningwebdev on 2023-07-05T23:28:42-05:00

app = "learningwebdev"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "scl"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
